### ISSUE TITLE
any idea how to access repository or services in a task?

### ISSUE THREAD

**Issue by thg303** [erickponce/nestjs-kue#1]
I have tried this but Nest can not resolve the dependency.

```
@Component()
export class PolicyTasks {
  constructor(
    private logger: Logger,
    private userRepository: UserRepository
  ) {}
//...
}
```

**Comment by erickponce** [comment]
Hi @thg303 !

The component where the tasks are defined, is a normal component, so it just need to be included on corresponding module for nest to load  it.

**Comment by thg303** [comment]
hi @erickponce 
you're right. I made a [sample repository](https://github.com/thg303/nestjs-kue-example) and it uses the service.

**Comment by thg303** [comment]
no problem dude ;)
