### ISSUE TITLE
Get job by ID

### ISSUE THREAD

**Issue by artjomzab** [erickponce/nestjs-kue#2]
@erickponce Could we extend KueService to have a getJob method? 

    getJob(id: string): kue.Job {
        return kue.Job.get(id, (err, job) => {
            if (err) throw err;
            return job;
        })
    }

**Comment by erickponce** [comment]
Interesting, I'll investigate this possibility.

**Comment by artjomzab** [comment]
@erickponce I am referring to this method https://github.com/Automattic/kue/blob/87d61503d3d9cc024633efc7611bd25551f0f87d/lib/queue/job.js#L152

**Comment by artjomzab** [comment]
I created a PR https://github.com/erickponce/nestjs-kue/pull/5
